version: '3.7'

services:
  heimdall-proxy:
    build:
      dockerfile: ${HEIMDALL_PATH:-.}/docker/nginx/Dockerfile
      context: ${HEIMDALL_PATH:-.}
      target: dev
    ports:
      - ${HEIMDALL_NGINX_PORT:-80}:80
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      APP_CONTAINER: heimdall-node

  heimdall-node:
    image: heimdall-node:latest
    build:
      dockerfile: Dockerfile
      context: ${HEIMDALL_PATH:-.}/docker/node
      target: dev
    volumes:
      - ${HEIMDALL_PATH:-./}:/srv/heimdall/current:cached
    expose:
      - 1337
    environment:
      UID: "${USER_UID?-Please export your UID in env var USER_UID}"
      GID: "${USER_GID?-Please export your GID in env var USER_GID}"
      APP_MODE: dev
      APP_DOMAIN: localhost
      DOCKER_API_URL: "http://localhost:${HEIMDALL_NGINX_PORT:-80}/docker/"
